#!/usr/bin/env bash
## Description:Apply a Drupal Recipe from recipes/custom folder.
## Usage: recipe-custom
## Example: ddev recipe-custom RECIPE

DOCROOT_PATH="${DDEV_COMPOSER_ROOT}/${DOCROOT}"
cd ${DOCROOT_PATH}

php core/scripts/drupal recipe recipes/custom/"$@"

drush cr
