#!/bin/bash
#ddev-generated
## Description:Apply a Drupal Recipe from recipes/custom folder.
## Usage: recipe-custom [args]
## Example: ddev recipe-custom RECIPE
## ExecRaw: true
## Flags: []

DOCROOT_PATH="${DDEV_COMPOSER_ROOT}/${DOCROOT}"
cd ${DOCROOT_PATH}

if [ $# -eq 0 ] ; then
  echo "You must provide a custom recipe."
  exit 1
fi

php core/scripts/drupal recipe recipes/custom/"$@"

drush cr
